### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by elieobeid7** [Jiro-Commerce/Jiro#1]
You say that the documentation is on Laravel's website, and if I click on the link that says documentation on your heroku website, there's nothing 

http://jiro-commerce.herokuapp.com/docs/0.1.0

What I'm trying to say is that there's no real documentation for the project itself

**Comment by andrewmclagan** [comment]
that is yet to come, we are in very very early stages. 

please see jiro.andrewmclagan.com
