### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by andrewmclagan** [Jiro-Commerce/Jiro#7]
We needs someone to setup Travis CI on all packages.

**Comment by thattomperson** [comment]
I'll set up travis and added the `build passing` images to packages as they are split into repos

**Comment by andrewmclagan** [comment]
Ok, that would be great. The build will currently fail as still very early stages :)

**Comment by andrewmclagan** [comment]
I just took care of this. Was pretty straight forward anyway.
