### ISSUE TITLE
How far is this from launch? and how can I be a contributor?

### ISSUE THREAD

**Issue by usamanoman** [Jiro-Commerce/Jiro#9]
I am dying to use this! I would like to know when you guys are planning to launch it. I would also love to be a contributor to the application. How would I know things needs to be done?

**Comment by fahmilatib** [comment]
Looks like this has been abandoned?

**Comment by andrewmclagan** [comment]
That is correct. At present our developers are involved with other projects /communities. If there were ever any serious momentum, comments or desire for a package based, extensible e-commerce platform we would revisit
